Blog_Post/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog_posts.urls'))
]

blog_posts/urls.py
from django.urls import path


from . import views
app_name = 'blog_posts'
urlpatterns = [
	# Home Page
	path('', views.index, name='index'),
	path('topics/', views.topics, name='topics'),
]

blog_posts/models.py
from django.db import models

# Create your models here.
class Topic(models.Model):
	topic = models.CharField(max_length=200)
	date_added = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return self.topic

class Entry(models.Model):
	topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
	text = models.TextField()
	date_added = models.DateTimeField(auto_now_add=True)

	class Meta:
		verbose_name_plural = 'Entries'

	def __str__(self):
		return f"{self.text[:50]}..."

blog_posts/views.py
from django.shortcuts import render

from .models import Topic
# Create your views here.

def index(request):
	return render(request, 'blog_posts/index.html')

def topics(request):
	topics = Topic.objects.all()
	context = {'topics': topics}
	return render(request, 'blog_posts/topics.html', context)

blog_posts/templates/blog_posts/base.html
<p>
	<a href="{% url 'blog_posts:index' %}">Blog</a> -
	<a href="{% url 'blog_posts:topics' %}">Topics</a>
</p>

{% block content %}{% endblock content %}

blog_posts/templates/blog_posts/index.html
{% extends 'blog_posts/base.html' %}

{% block content %}

<p>Welcome to my Blog site</p>

{% endblock content %}

blog_posts/templates/blog_posts/topics.html
{% extends 'blog_posts/base.html' %}

{% block content %}

<p>Topics:</p>

<ul>
	{% for topic in topics %}
	  <li>{{ topic }}</li>
	{% empty %}
	  <li>No topics yet</li>
	{% endfor %}
</ul>


{% endblock content %}